server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  elasticsearch:
    uris: http://localhost:9200
  application:
    name: artman-back-end
  datasource:
    url:
      jdbc:mysql://localhost:3306/artman?
      useUnicode=true&
      characterEncoding=utf-8&
      serverTimezone=Asia/Shanghai&
      autoReconnect=true&
      rewriteBatchedStatements=true&
      useSSL=false
    username: root
    password: alpine
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.CompositeEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  type-aliases-package: cn.edu.hit.artman.pojo.po.*

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5t85whiXGeCFrgYEcHnH
    accessKeySecret: ycfETRDKzFXst6ft0RLExfUHL5fD0q
    bucketName: artman
    urlPrefix: https://artman.oss-cn-beijing.aliyuncs.com/
